blah_blah_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog_urls'),
    path('accounts/', include('allauth.urls')),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.PostList.as_view(), name="home"),
    path("profile/", views.PostListProfile.as_view(), name="profile"),
    path("blog_form/", views.create_post, name="blog_form"),
    path("edit_post_form/<slug:slug>/", views.edit_post, name="edit_post_form"),
    path("delete_post/<slug:slug>/", views.delete_post, name="delete_post"),
    path("category/<slug:genre>/", views.post_category, name="category"),
    path("<slug:slug>/", views.PostDetail.as_view(), name="post_detail"),
    path("like/<slug:slug>/", views.Postlike.as_view(), name="post_like"),
    path("dislike/<slug:slug>/", views.Postdislike.as_view(), name="post_dislike"),
]


handler404 = "blog.views.page_not_found_view"

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))

MEDIATYPE = ((0, "Film"), (1, "Tv"), (2, "Book"), (3, "other"))

GENRE = (
    (0, "Action"),
    (1, "Adventure"),
    (2, "Sci-fi"),
    (3, "Horror"),
    (4, "Romantic"),
    (5, "Comedy"),
    (6, "Drama"),
    (7, "Thriller"),
    (8, "Rom-com"),
    (9, "Classic"),
    (10, "Historical"),
    (11, "Documentary"),
    (12, "Other"),
)


ISSUE_TYPE = ((0, "Post"), (1, "Comment"), (2, "User"), (3, "Profile"), (4, "Other"))


class Post(models.Model):
    """
    Post model
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    name_of_show_or_film = models.CharField(max_length=200, unique=True)
    media_type = models.IntegerField(choices=MEDIATYPE, default=0)
    genre = models.IntegerField(choices=GENRE, default=0)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    featured_image = CloudinaryField("image", default="placeholder")
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name="blogpost_like", blank=True)
    dislikes = models.ManyToManyField(User, related_name="blogpost_dislike", blank=True)


    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

    def number_of_dislikes(self):
        return self.dislikes.count()


class Comment(models.Model):
    """
    Comment model
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"


class Contact(models.Model):
    name = models.CharField(max_length=200, unique=True)
    username = models.CharField(max_length=200, unique=True)
    related_post = models.CharField(max_length=200, unique=True)
    related_author = models.CharField(max_length=200, unique=True)
    issue_type = models.IntegerField(choices=ISSUE_TYPE, default=0)
    issue_details = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django import forms
from .models import Comment, Post, Contact


class CommentForm(forms.ModelForm):

    """
    Comment Form
    """

    class Meta:

        """
        Meta Class
        """

        model = Comment
        fields = ('body', )


class PostForm(forms.ModelForm):

    """
    Post Form
    """

    class Meta:

        """
        Meta Class
        """

        model = Post
        fields = (
            'featured_image',
            'title',
            'media_type',
            'genre',
            'name_of_show_or_film',
            'content',
            'status',
            )

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.views.generic import CreateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from .models import Post
from .forms import CommentForm, PostForm
from django.utils.text import slugify


def create_post(request):
    """
    renders create post page
    """
    post_form = PostForm(request.POST or None, request.FILES or None)
    context = {
        "post_form": post_form,
    }

    if request.method == "POST":
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            post_form = post_form.save(commit=False)
            post_form.author = request.user
            post_form.slug = slugify(post_form.title)
            post_form.save()
            return redirect("home")
    else:
        post_form = PostForm()
    return render(request, "blog_form.html", context)


def edit_post(request, slug):
    """
    renders edit post page
    """
    post = get_object_or_404(Post, slug=slug)
    post_form = PostForm(request.POST or None, instance=post)
    context = {"post_form": post_form, "post": post}

    if request.method == "POST":
        post_form = PostForm(request.POST, request.FILES, instance=post)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("profile")
    else:
        post_form = PostForm(instance=post)
    return render(request, "edit_post_form.html", context)


def delete_post(request, slug):
    """
    Deletes post
    """

    post = get_object_or_404(Post, slug=slug)
    context = {"post": post}
    if request.method == "POST":
        post.delete()
        return redirect("profile")
    else:
        return render(request, "delete_post.html", context)


def post_category(request, genre):
    """ 
    Category list view
    """
    category_posts = Post.objects.filter(genre=genre, status=1).order_by("-created_on")
    return render(request, 'category.html', {'genre': genre, 'category_posts': category_posts})


def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)


class PostListProfile(generic.ListView):
    """
    Profile post list
    """
    model = Post
    queryset = Post.objects.order_by("-created_on")
    template_name = "profile.html"
    paginate_by = 8


class PostList(generic.ListView):
    """
    Index post list
    """
    model = Post
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "index.html"
    paginate_by = 8


class PostDetail(View):
    """
    Post detail view
    """
    def get(self, request, slug, *args, **kwargs):
        """
        Gets post details
        """
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("created_on")

        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        disliked = False
        if post.dislikes.filter(id=self.request.user.id).exists():
            disliked = True

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "disliked": disliked,
                "comment_form": CommentForm(),
            },
        )

    def post(self, request, slug, *args, **kwargs):
        """
        Post comments
        """
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.order_by("created_on")

        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        disliked = False
        if post.dislikes.filter(id=self.request.user.id).exists():
            disliked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": True,
                "posted": True,
                "liked": liked,
                "disliked": disliked,
                "comment_form": CommentForm(),
            },
        )


class Postlike(View):
    """
    Like details
    """
    def post(self, request, slug, *args, **kwargs):
        """
        Post like
        """
        post = get_object_or_404(Post, slug=slug)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)
            post.dislikes.remove(request.user)

        return HttpResponseRedirect(reverse("post_detail", args=[slug]))


class Postdislike(View):
    """
    Dislike details
    """
    def post(self, request, slug, *args, **kwargs):
        """
        Post dislike
        """
        post = get_object_or_404(Post, slug=slug)
        if post.dislikes.filter(id=request.user.id).exists():
            post.dislikes.remove(request.user)
        else:
            post.dislikes.add(request.user)
            post.likes.remove(request.user)

        return HttpResponseRedirect(reverse("post_detail", args=[slug]))

templates/blog_form.html
{% extends 'base.html' %} {% block content %} {% if user.is_authenticated %} {% load crispy_forms_tags %} <div class="container px-3 my-5 ">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="card border-0 rounded-3 shadow-lg">
        <div class="card-body p-4 ">
          <div class="text-center">
            <div class="h1 fw-light">Create a blog post</div>
            <p class="mb-4 text-muted">Write you post below, remember to fill in all the criteria.</p>
          </div>
          <p>Posting as: {{ user.username }}</p>
          <form class="contactForm " data-sb-form-api-token="API_TOKEN" method="post" enctype="multipart/form-data">
            {{ post_form | crispy }} {% csrf_token %} <button class="btn btn-lg btn-primary btn-login text-uppercase fw-bold my-2 " type="submit" value="Save">Add Blog post</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script> 
{% else %} {% endif %} {% endblock %}

templates/category.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %} <section class="py-4">
   <div class="container">
     <h1 class="fw-light">Post & Discuss all your favorite movies, TV shows, books and more!</h1>
     <p class="lead">Blah Blah Blog is the place to make your case or argue your point!</p>
     <h1>{{ post.get_genre_display }}</h1>
   </div>
 </section>
 <div class="container">
   <div class="row"> {% for post in category_posts %} <div class="col-xl-3 col-md-6 mb-4">
       <div class="card border-0 shadow">
         <a href="{% url 'post_detail' post.slug %}"> {% if "placeholder" in post.featured_image.url %} <img src="https://images.pexels.com/photos/5662857/pexels-photo-5662857.png?cs=srgb&dl=pexels-tima-miroshnichenko-5662857.jpg&fm=jpg" class="card-img-top" alt="..."> {% else %} <img class="card-img-top" src=" {{ post.featured_image.url }}"> {% endif %} </a>
         <div class="card-body text-center">
           <h5 class="card-title mb-0">{{ post.title }}</h5>
           <h6 class="card-text text-black-50">{{ post.get_media_type_display }} | {{ post.name_of_show_or_film }} | {{ post.get_genre_display }}</h6>
           <h6 class="card-text text-black-50">Author: {{ post.author }}</h6>
           <hr />
           <p class="card-text text-muted h6">Posted:{{ post.created_on|date:"d/m/y at H:i"}}</p>
           <i class="far fa-smile"></i>
           {{ post.number_of_likes }}
           <i class="far fa-frown"></i>
           {{ post.number_of_dislikes }}
           </a>
         </div>
       </div>
     </div> {% if forloop.counter|divisibleby:4 %} </div>
   <div class="row"> {% endif %} {% endfor %} </div> {% if is_paginated %} <nav aria-label="Page navigation">
     <ul class="pagination justify-content-center"> {% if page_obj.has_previous %} <li>
         <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a>
       </li> {% endif %} {% if page_obj.has_next %} <li>
         <a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a>
       </li> {% endif %} </ul>
   </nav> {% endif %}
 </div> {%endblock%}

templates/contact.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %} {% if user.is_authenticated %} 
<div class="col-md-4 card mb-4  mt-3 ">
   <div class="card-body">
     <h3>Contact Us:</h3>
     <p>Posting as: {{ user.username }}</p>
     <form method="post" style="margin-top: 1.3em;">
       {{ contact_form | crispy }} {% csrf_token %} <button type="submit" class="btn btn-signup btn-lg">Submit</button>
     </form> {% endif %}
   </div>
 </div> 
 {% endblock %}

templates/delete_post.html
{% extends 'base.html' %} {% block content %} {% if user.is_authenticated %} {% load crispy_forms_tags %} <div class="container px-5 my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="card border-0 rounded-3 shadow-lg">
        <div class="card-body p-4">
          <div class="text-center">
            <div class="h1 fw-light">Delete blog post</div>
          </div>
          <p>{{ user.username }} Are you sure you want to delete this post: {{ post.title }} </p>
          <form class="contactForm" data-sb-form-api-token="API_TOKEN" method="post" enctype="multipart/form-data"> {% csrf_token %} <a class="dropdown-item" href="{% url 'profile' %}">
              <strong>No</strong> go back to My Profile! </a>
            <br>
            <button class="btn btn-secondary right mb-2" type="submit" value="Save">Yes <strong>Delete</strong> this Blog post </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script> 
{% else %} {% endif %} {% endblock %}

templates/edit_post_form.html
{% extends 'base.html' %} {% block content %} {% if user.is_authenticated %} {% load crispy_forms_tags %} <div class="container px-5 my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="card border-0 rounded-3 shadow-lg">
        <div class="card-body p-4">
          <div class="text-center">
            <div class="h1 fw-light">Edit blog post</div>
            <p class="mb-4 text-muted">Edit your post below, remember to fill in all the criteria.</p>
          </div>
          <p>Posting as: {{ user.username }}</p>
          <form class="contactForm" data-sb-form-api-token="API_TOKEN" method="post" enctype="multipart/form-data">
            {{ post_form | crispy }} {% csrf_token %} <button class="btn btn-secondary right mb-2" type="submit" value="Save">Edit Blog post</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script> 
{% else %} {% endif %} {% endblock %}

templates/index.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %} <section class="py-4">
   <div class="container">
     <h1 class="fw-light">Post & Discuss all your favorite movies, TV shows, books and more!</h1>
     <p class="lead">Blah Blah Blog is the place to make your case or argue your point!</p>
   </div>
 </section>
 <div class="container">
   <div class="row"> {% for post in post_list %} <div class="col-xl-3 col-md-6 mb-4">
       <div class="card border-0 shadow">
         <div class="embed-responsive embed-responsive-16by9">
           <a href="{% url 'post_detail' post.slug %}"> {% if "placeholder" in post.featured_image.url %} <img src="https://images.pexels.com/photos/5662857/pexels-photo-5662857.png?cs=srgb&dl=pexels-tima-miroshnichenko-5662857.jpg&fm=jpg" class="card-img-top embed-responsive-item" alt="placeholder"> {% else %} <img class="card-img-top embed-responsive-item " src=" {{ post.featured_image.url }}"> {% endif %} </a>
         </div>
         <div class="card-body text-center">
           <h5 class="card-title mb-0">{{ post.title }}</h5>
           <h6 class="card-text text-black-50">{{ post.name_of_show_or_film }} | {{ post.get_media_type_display }} | <a href="{% url 'category' post.genre %}">{{ post.get_genre_display }}</a>
           </h6>
           <h6 class="card-text text-black-50">Author: {{ post.author }}</h6>
           <hr />
           <p class="card-text text-muted h6">Posted:{{ post.created_on|date:"d/m/y at H:i"}}</p>
           <i class="far fa-smile"></i>
           {{ post.number_of_likes }}
           <i class="far fa-frown"></i>
           {{ post.number_of_dislikes }}
           </a>
         </div>
       </div>
     </div> {% if forloop.counter|divisibleby:4 %} </div>
   <div class="row"> {% endif %} {% endfor %} </div> {% if is_paginated %} <nav aria-label="Page navigation">
     <ul class="pagination justify-content-center"> {% if page_obj.has_previous %} <li>
         <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-lg btn-primary btn-login text-uppercase fw-bold mb-2">&laquo; PREV </a>
       </li> {% endif %} {% if page_obj.has_next %} <li>
         <a href="?page={{ page_obj.next_page_number }}" class="btn btn-lg btn-primary btn-login text-uppercase fw-bold mb-2"> NEXT &raquo;</a>
       </li> {% endif %} </ul>
   </nav> {% endif %}
 </div> {%endblock%}

templates/post_detail.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %} <div class="container">
   <h1 class="my-4">{{ post.name_of_show_or_film }}</h1>
   <div class="row">
     <div class="d-inline-block d-md-block col-md-6 col-sm-12 masthead-image"> {% if "placeholder" in post.featured_image.url %} <img src="https://images.pexels.com/photos/33129/popcorn-movie-party-entertainment.jpg?cs=srgb&dl=pexels-pixabay-33129.jpg&fm=jpg" width="100%" class="img-fluid"> {% else %} <img src=" {{ post.featured_image.url }}" width="100%" class="img-fluid"> {% endif %} </div>
     <div class="col-md-4 col-sm-12">
       <h3 class="my-3">Posted by: {{ post.author }}</h3>
       <p>On: {{ post.created_on|date:"d/m/y" }}</p>
       <h3 class="my-3">Post Details</h3>
       <ul>
         <li>Media: {{ post.get_media_type_display }}</li>
         <li>Genre: <a href="{% url 'category' post.genre %}">{{ post.get_genre_display }}</a>
         </li>
       </ul>
     </div>
   </div>
   <div class="container">
     <div class="row">
       <div class="col card mb-4  mt-3 left  top">
         <div class="card-body">
           <h3>
             {{post.title}}
           </h3 class="card-text ">
           <p class="card-text ">
             {{ post.content | safe }}
           </p>
           <div class="row">
             <div class="col-4">
               <strong> {% if user.is_authenticated %} <form class="d-inline" action="{% url 'post_like' post.slug %}" method="POST"> {% csrf_token %} {% if liked %} <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like">
                     <i class="fas fa-smile"></i>
                   </button>
                   <span class="text-secondary">{{ post.number_of_likes }}</span> {% else %} <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like">
                     <i class="far fa-smile"></i>
                   </button>
                   <span class="text-secondary">{{ post.number_of_likes }}</span> {% endif %}
                 </form>
                 <form class="d-inline" action="{% url 'post_dislike' post.slug %}" method="POST"> {% csrf_token %} {% if disliked %} <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like">
                     <i class="fas fa-frown"></i>
                   </button>
                   <span class="text-secondary">{{ post.number_of_dislikes }}</span> {% else %} <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like">
                     <i class="far fa-frown"></i>
                   </button>
                   <span class="text-secondary">{{ post.number_of_dislikes }}</span> {% endif %}
                 </form> {% else %} <span class="text-secondary">
                   <i class="far fa-smile"></i>
                 </span>
                 <span class="text-secondary">{{ post.number_of_likes }}</span>
                 <span class="text-secondary">
                   <i class="far fa-frown"></i>
                 </span>
                 <span class="text-secondary">{{ post.number_of_dislikes }}</span> {% endif %}
               </strong>
             </div>
           </div>
         </div>
       </div>
     </div>
     <div class="row">
       <div class="col">
         <hr>
       </div>
     </div> {% if commented %}. <div class="container">
       <div class="row">
         <div class="col-md-8 offset-md-2">
           <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert"> Comment posted successfully <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
           </div>
         </div>
       </div>
     </div> {% else %} {% endif %} <div class="row">
       <div class="col-md-6 card mb-1  mt-1 col-sm-10">
         <div class="card border-0 rounded-3 shadow-lg">
           <div class="col-6">
             <h3>Comments:</h3> {% with comments.count as total_comments %} <strong class="text-secondary">
               <i class="far fa-comments"></i>
               {{ total_comments }}
             </strong> {% endwith %}
           </div>
           <div class="card-body"> {% for comment in comments %} <div class="card border-0 rounded-3 shadow-lg my-1">
               <div class="comments" style="padding: 10px;">
                 <p class="font-weight-bold">
                   {{ comment.name }}
                   <span class=" text-muted font-weight-normal">
                     {{ comment.created_on|date:"d/m/y h:i a"}}
                   </span> wrote:
                 </p>
                 {{ comment.body | linebreaks }}
               </div>
             </div> {% endfor %} </div>
         </div>
       </div> {% if user.is_authenticated %} <div class="col-md-6 card mb-4  mt-3 col-sm-10">
         <div class="card border-0 rounded-3 shadow-lg">
           <div class="card-body">
             <h3>Leave a comment:</h3>
             <p>Posting as: {{ user.username }}</p>
             <form method="post" style="margin-top: 1.3em;">
               {{ comment_form | crispy }} {% csrf_token %} <button type="submit" class="btn btn-lg btn-primary btn-login text-uppercase fw-bold my-2">Submit</button>
             </form>
           </div> {% endif %}
         </div>
       </div>
     </div>
   </div> {% endblock content %}

templates/profile.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %} <div class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container">
      <p class="navbar-brand">Profile: {{ user.username }}</p>
    </div>
  </div>
  <div class="container">
    <div class="row"> {% for post in user.blog_posts.all %} <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-0 shadow"> {% if post.status == 1 %} <a href="{% url 'post_detail' post.slug %}"> {% if "placeholder" in post.featured_image.url %} <img src="https://images.pexels.com/photos/5662857/pexels-photo-5662857.png?cs=srgb&dl=pexels-tima-miroshnichenko-5662857.jpg&fm=jpg" class="card-img-top" alt="..."> {% else %} <img class="card-img-top" src=" {{ post.featured_image.url }}"> {% endif %} </a> {% else %} <a href="{% url 'edit_post_form' post.slug %}"> {% if "placeholder" in post.featured_image.url %} <img src="https://images.pexels.com/photos/5662857/pexels-photo-5662857.png?cs=srgb&dl=pexels-tima-miroshnichenko-5662857.jpg&fm=jpg" class="card-img-top" alt="..."> {% else %} <img class="card-img-top" src=" {{ post.featured_image.url }}"> {% endif %} </a> {% endif %} <div class="card-body text-center">
            <h5 class="card-title mb-0">{{ post.title }}</h5>
            <h6 class="card-text text-black-50">{{ post.name_of_show_or_film }} | {{ post.get_media_type_display }} | <a href="{% url 'category' post.genre %}">{{ post.get_genre_display }}</a>
            </h6>
            <h6 class="card-text text-black-50">Author: {{ post.author }}
              <a href="{% url 'edit_post_form' post.slug %}">
                <small>(edit)</small>
              </a>
              <a href="{% url 'delete_post' post.slug %}">
                <small>(delete)</small>
              </a>
            </h6>
            <h6 class="card-text text-black-50">{{ post.get_status_display }}</h6> {% if post.status == 1 %}
            <hr />
            <p class="card-text text-muted h6">Posted:{{ post.created_on|date:"d/m/y at H:i"}}</p>
            <i class="far fa-smile"></i>
            {{ post.number_of_likes }}
            <i class="far fa-frown"></i>
            {{ post.number_of_dislikes }} {% else %} {% endif %} </a>
          </div>
        </div>
      </div> {% if forloop.counter|divisibleby:4 %} </div>
    <div class="row"> {% endif %} {% endfor %} </div> {% if is_paginated %} <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center"> {% if page_obj.has_previous %} <li>
          <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-lg btn-primary btn-login text-uppercase fw-bold mb-2">&laquo; PREV </a>
        </li> {% endif %} {% if page_obj.has_next %} <li>
          <a href="?page={{ page_obj.next_page_number }}" class="btn btn-lg btn-primary btn-login text-uppercase fw-bold mb-2"> NEXT &raquo;</a>
        </li> {% endif %} </ul>
    </nav> {% endif %}
  </div> {%endblock%}